config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  get '/bike-shop', to: 'accessories#index'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/dashboard', to: 'users#dashboard'
  resources :users, only: [:new, :create, :edit, :update]
  resources :stations, only: [:index]
  resources :trips, only: [:show, :index]
  resources :conditions, only: [:index, :show]
  get '/conditions-dashboard', to: 'conditions#dashboard'
  resources :accessories, only: [:show]
  resources :carts, only: [:create]
  namespace :admin do
    resources :stations, only: [:new, :edit, :create, :update, :destroy]
    resources :trips, only: [:new, :edit, :create, :update, :destroy]
    resources :conditions, only: [:new, :edit, :create, :update, :destroy]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:update]
    get '/bike-shop/new', to: 'accessories#new'
    post '/bike-shop', to: 'accessories#create'
    get '/bike-shop', to: 'accessories#index'
  end
  get '/admin/dashboard', to: 'admin/users#dashboard'
  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  resources :orders, only: [:create, :show]
  get '/:id', to: 'stations#show', as: :station
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  validates_presence_of :name
  validates_presence_of :dock_count
  validates_presence_of :city
  validates_presence_of :installation_date

  has_many :trips
  has_many :trips, class_name: 'Trip', foreign_key: :start_station_id
  has_many :trips, class_name: 'Trip', foreign_key: :end_station_id
  has_many :statuses

  friendly_id :name, use: :slugged

  def self.total_count
    count
  end

  def self.average_bikes_per_station
    average(:dock_count).round(1)
  end

  def self.station_with_most_bikes
    order(:dock_count).last
  end

  def self.station_with_least_bikes
    order(:dock_count).first
  end

  def self.newest_station
    order(:installation_date).last
  end

  def self.oldest_station
    order(:installation_date).first
  end

  def rides_started_here
    Trip.where(start_station_id: id).count
  end

  def rides_ended_here
    Trip.where(end_station_id: id).count
  end

  def frequent_destination_station
    start_trips = Trip.where(start_station_id: id)
    end_trip = start_trips.select('end_station_id, COUNT(end_station_id) AS end_station_count')
                .group(:end_station_id)
                .order('end_station_count DESC')
                .limit(1)
                .first
    Station.find(end_trip.end_station_id)
  end

  def frequent_origination_station
    end_trips = Trip.where(end_station_id: id)
    start_trip = end_trips.select('start_station_id, COUNT(start_station_id) AS start_station_count')
                .group(:start_station_id)
                .order('start_station_count DESC')
                .limit(1)
                .first
    Station.find(start_trip.start_station_id)
  end

  def date_with_most_trips
    start_trips = Trip.where(start_station_id: id)
    start_trips.select('start_date, COUNT(start_date) AS start_date_count')
                .group(:start_date)
                .order('start_date_count DESC')
                .limit(1)
                .take
                .start_date
  end

  def zip_code_with_most_trips
    start_trips = Trip.where(start_station_id: id)
    start_trips.select('zip_code, COUNT(zip_code) AS zip_code_count')
                .group(:zip_code)
                .order('zip_code_count DESC')
                .limit(1)
                .take
                .zip_code
  end

  def bike_id_with_most_trips
    start_trips = Trip.where(start_station_id: id)
    start_trips.select('bike_id, COUNT(bike_id) AS bike_id_count')
                .group(:bike_id)
                .order('bike_id_count DESC')
                .limit(1)
                .take
                .bike_id
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Successfully created #{@station.name}"
      redirect_to station_path(@station)
    else
      flash[:notice] = "Station not created, try again"
      render :new
    end
  end

  def edit
    @station = Station.find_by(slug: params[:id])
  end

  def update
    @station = Station.find_by(slug: params[:id])
    if @station.update(station_params)
      @station.update(slug: params[:name])
      flash[:notice] = "Successfully updated #{@station.name}"
      redirect_to station_path(@station)
    else
      flash[:notice] = "Station was not updated. Try again."
      render :edit
    end
  end

  def destroy
    station = Station.find_by(slug: params[:id])
    station.destroy
    flash[:notice] = "You have successfully deleted #{station.name}"
    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:name, :city, :dock_count, :installation_date)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :require_registered_user, only: [:dashboard]

  def show
    @station = Station.friendly.find(params[:id])
  end

  def index
    @stations = Station.all
  end

  def dashboard
    @stations = Station.all
    @stations_count = @stations.total_count
    @avg_bikes = @stations.average_bikes_per_station
    @station_most_bikes = @stations.station_with_most_bikes
    @station_least_bikes = @stations.station_with_least_bikes
    @newest_station = @stations.newest_station
    @oldest_station = @stations.oldest_station
  end
end

app/views/stations/dashboard.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'>Stations Dashboard</h1>
</header>
<header class=''>
</header>
<div class="">
  <section class="container-fluid">
    <div class="row">
      <div class="col-3"></div>
      <table id="max-temps" class="table table-striped col-6 margin-right-20">
        <thead class="thead-dark" id="max-temps">
          <tr>
            <th scope="col">Station Stats</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Total Station Count: </td>
            <td><%= @stations_count %></td>
          </tr>
          <tr>
            <td>Average Bikes Per Station: </td>
            <td><%= @avg_bikes %></td>
          </tr>
          <tr>
            <td>Most Bikes Per Station: </td>
            <td><%= @station_most_bikes.dock_count %></td>
          </tr>
          <tr>
            <td>Station With Most Bikes: </td>
            <td><%= @station_most_bikes.name %></td>
          </tr>
          <tr>
            <td>Least Bikes Per Station: </td>
            <td><%= @station_least_bikes.dock_count %></td>
          </tr>
          <tr>
            <td>Station With Least Bikes: </td>
            <td><%= @station_least_bikes.name %></td>
          </tr>
          <tr>
            <td>Newest Station: </td>
            <td><%= @newest_station.name %></td>
          </tr>
          <tr>
            <td>Oldest Station: </td>
            <td><%= @oldest_station.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>
<header class=''>
</header>
<header class=''>
</header>
<nav class="navbar navbar-dark bg-dark height-40"></nav>

app/views/stations/index.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'>Stations</h1>
  <% if admin_user? %>
    <%= link_to 'Create New Station', new_admin_station_path, class:'btn btn-secondary' %>
  <% end %>
</header>

<section class='station-index-main'>
  <table class="table table-striped table-ligth" id='station-index-table'>
    <thead class='table-light table-header'>
      <tr>
        <th scope="col" id='table-entry'>Station</th>
        <th scope="col" id='table-entry'>City</th>
        <th scope="col" id='table-entry'>Dock Count</th>
        <th scope="col" id='table-entry'>Installation Date</th>
        <% if admin_user? %>
        <th></th>
        <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @stations.each do |station| %>
      <tr>
        <th id='table-entry'><%= link_to station.name, station_path(station) %></th>
        <td id='table-entry'><%= station.city %></td>
        <td id='table-entry'><%= station.dock_count %></td>
        <td id='table-entry'><%= station.installation_date.strftime('%m/%d/%Y') %></td>
        <% if admin_user? %>
        <td><%= button_to 'Edit', edit_admin_station_path(station), method: :get, class:'btn btn-success edit-button' %></td>
        <td><%= button_to 'Delete', admin_station_path(station), method: :delete, data: {confirm: "Really want to delete this station?"}, class:'btn btn-danger delete-button' %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/stations/show.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'><%= @station.name %></h1>
  <% if admin_user? %>
    <%= link_to 'Create New Station', new_admin_station_path, class:'btn btn-secondary' %>
  <% end %>
</header>

<section class='show-main'>
  <div class="show-info">
    <div class="">Dock Count: <%= @station.dock_count %></div>
    <div class="">City: <%= @station.city %></div>
    <div class="">Installation Date: <%= @station.installation_date.strftime("%m/%d/%Y") %></div>
    <div class="">Number of Rides Started Here: <%= @station.rides_started_here %></div>
    <div class="">Number of Rides Ended Here: <%= @station.rides_ended_here %></div>

    <% unless @station.trips.empty? %>
      <div class="">Most Popular Place to Go From Here: <%= @station.frequent_destination_station.name %></div>
      <div class="">Where Most Trips Come From: <%= @station.frequent_origination_station.name %></div>
      <div class="">Date with the Most Trips Started Here: <%= @station.date_with_most_trips.strftime('%m/%d/%Y') %></div>
      <div class="">Most Frequent Zip Code of Users Starting Here: <%= @station.zip_code_with_most_trips %></div>
      <div class="">Bike Id Starting Here Most Frequently: <%= @station.bike_id_with_most_trips %></div>
    <% end %>
  </div>
  <p><%= link_to '<< Back to Stations Index', stations_path %></p>
</section>

<div class="show-buttons">
  <div class="button-group">
    <% if admin_user? %>
    <%= button_to 'Edit', edit_admin_station_path(@station), method: :get, class:'btn btn-success show-edit-button' %>
    <%= button_to 'Delete', admin_station_path(@station), method: :delete, data: {confirm: "Really want to delete this station?"}, class:'btn btn-danger' %>
    <% end %>
  </div>
</div>