config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  get '/bike-shop', to: 'accessories#index'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/dashboard', to: 'users#dashboard'
  resources :users, only: [:new, :create, :edit, :update]
  resources :stations, only: [:index]
  resources :trips, only: [:show, :index]
  resources :conditions, only: [:index, :show]
  get '/conditions-dashboard', to: 'conditions#dashboard'
  resources :accessories, only: [:show]
  resources :carts, only: [:create]
  namespace :admin do
    resources :stations, only: [:new, :edit, :create, :update, :destroy]
    resources :trips, only: [:new, :edit, :create, :update, :destroy]
    resources :conditions, only: [:new, :edit, :create, :update, :destroy]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:update]
    get '/bike-shop/new', to: 'accessories#new'
    post '/bike-shop', to: 'accessories#create'
    get '/bike-shop', to: 'accessories#index'
  end
  get '/admin/dashboard', to: 'admin/users#dashboard'
  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  resources :orders, only: [:create, :show]
  get '/:id', to: 'stations#show', as: :station
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def add_accessory(id)
    @contents[id.to_s] ||= 0
    @contents[id.to_s] += 1
    @contents
  end

  def total_count
    @contents.values.sum
  end

  def count_of(id)
    @contents[id.to_s].to_i
  end

  def make_accessories
    Accessory.where(id: @contents.keys)
  end

  def subtotal(accessory)
    @contents[accessory.id.to_s] * accessory.price
  end

  def grand_total(all_accessories)
    all_accessories.inject(0) do |sum, accessory|
       sum += @contents[accessory.id.to_s] * accessory.price
    end
  end

  def remove_accessory(id)
    @contents.delete(id.to_s)
    @contents
  end

  def decrease_quantity(id)
    @contents[id.to_s] -= 1 if @contents[id.to_s] > 0
    remove_accessory(id) if @contents[id.to_s] <= 0
    @contents
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    accessory = Accessory.find(params[:accessory_id])

    session[:cart] = @cart.add_accessory(accessory.id)
    quantity = @cart.count_of(accessory.id)

    flash[:notice] = "You now have #{pluralize(quantity, accessory.title)} in your cart."
    if params[:in_cart]
      redirect_to cart_path
    elsif params[:on_show]
      redirect_to accessory_path(accessory)
    else
      redirect_to bike_shop_path
    end
  end

  def destroy
    accessory = Accessory.find(params[:accessory_id])
    if params[:remove] == "true"
      session[:cart] = @cart.remove_accessory(accessory.id)
      flash[:notice] = "Successfully removed #{accessory.title} from your cart."
      redirect_to cart_path(removed_id: accessory.id)
    else
      session[:cart] = @cart.decrease_quantity(accessory.id)
      redirect_to cart_path
    end
  end

  def show
    @removed_accessory = Accessory.find(params[:removed_id]) if params[:removed_id]
    @cart_accessories = @cart.make_accessories
  end
end

app/views/carts/show.html.erb
<% if @removed_accessory %>
<div class="alert alert-primary m-0" role="alert">Link to <%= link_to @removed_accessory.title, accessory_path(@removed_accessory) %> page.</div>
<% end %>
<header class='jumbotron' id='header'>
  <h1 class='text-white'>Your Cart</h1>
</header>
<div class=" d-flex flex-wrap justify-content-center">
<% @cart_accessories.each do |accessory| %>
      <article class="cart-accessory-<%= accessory.id %> m-5">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= accessory.image %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= accessory.title %></h5>
          <p class="card-text"><%= number_to_currency(accessory.price) %></p>
          <p class="card-text">Quantity: <%= @cart.count_of(accessory.id) %></p>
          <p class="card-text">Subtotal: <%= number_to_currency(@cart.subtotal(accessory)) %></p>
          <%= button_to "Increase Quantity", carts_path(accessory_id: accessory.id, in_cart: true), method: :post, class: 'btn btn-primary mb-1' %>
          <%= button_to "Decrease Quantity", cart_path(accessory_id: accessory.id), method: :delete, class: 'btn btn-primary mb-1' %>
          <%= button_to "Remove", cart_path(accessory_id: accessory.id, remove: true), method: :delete, class: 'btn btn-primary mb-1' %>
        </div>
      </div>
    </article>
  <% end %>
</div>
<h3 class="d-flex justify-content-center mb-4">Grand Total: <%= currency = number_to_currency(@cart.grand_total(@cart_accessories)) %></h3>
<% if current_user && !(@cart_accessories.empty?)%>
  <div class='d-flex justify-content-center'><%= button_to "Checkout", orders_path(grand_total: currency), method: :post, class: "btn btn-primary btn-lg mb-5" %></div>
<% elsif current_user.nil? %>
  <div class='d-flex justify-content-center'><%= button_to "Checkout", login_path, method: :get, class: "btn btn-primary btn-lg mb-5" %></div>
<% end %>