config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  get '/bike-shop', to: 'accessories#index'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/dashboard', to: 'users#dashboard'
  resources :users, only: [:new, :create, :edit, :update]
  resources :stations, only: [:index]
  resources :trips, only: [:show, :index]
  resources :conditions, only: [:index, :show]
  get '/conditions-dashboard', to: 'conditions#dashboard'
  resources :accessories, only: [:show]
  resources :carts, only: [:create]
  namespace :admin do
    resources :stations, only: [:new, :edit, :create, :update, :destroy]
    resources :trips, only: [:new, :edit, :create, :update, :destroy]
    resources :conditions, only: [:new, :edit, :create, :update, :destroy]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:update]
    get '/bike-shop/new', to: 'accessories#new'
    post '/bike-shop', to: 'accessories#create'
    get '/bike-shop', to: 'accessories#index'
  end
  get '/admin/dashboard', to: 'admin/users#dashboard'
  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  resources :orders, only: [:create, :show]
  get '/:id', to: 'stations#show', as: :station
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :password, :username, :email, :first_name, :last_name, :address
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  has_many :orders
  has_secure_password

  enum role: ['default', 'admin']
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def dashboard
    @orders = Order.all.includes(:order_accessories)
    @status_totals = @orders.orders_per_status if @orders
    if params[:status] == 'all'
      @orders
    elsif params[:status]
      @orders = Order.where(status: params[:status].to_i)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_registered_user, only: [:dashboard]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:notice] = "Invalid input. Please try again."
      render :new
    end
  end

  def edit
    render file: "/public/404", layout: false unless current_user.id == params[:id].to_i
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Successfully updated your account"
      redirect_to dashboard_path unless admin_user?
      redirect_to admin_dashboard_path if admin_user?
    else
      flash[:notice] = "Your account was not updated. Try again."
      render :edit
    end
  end

  def dashboard
    @orders = current_user.orders
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :first_name, :last_name, :address)
  end
end

app/views/admin/users/dashboard.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'>Admin Dashboard</h1>
</header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <ul class="navbar-nav col-10">
    <li class="nav-item">Name: <%= current_user.first_name.titleize %> <%= current_user.last_name.titleize %></li>
  </ul>
  <ul class="navbar-nav col-2">
    <li class="nav-item"><a href="<%= admin_bike_shop_path %>" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Admin Bike Shop</a></li>
  </ul>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <ul class="navbar-nav col-8">
    <li class="nav-item">Email: <%= current_user.email %></li>
  </ul>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white mb-5">
  <ul class="navbar-nav col-10">
    <li class="nav-item">Username: <%= current_user.username %></li>
  </ul>
  <ul class="navbar-nav col-1">
    <li class="nav-item">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter Orders by Status
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="/admin/dashboard?status=all">All</a>
          <a class="dropdown-item" href="/admin/dashboard?status=1">Ordered</a>
          <a class="dropdown-item" href="/admin/dashboard?status=2">Paid</a>
          <a class="dropdown-item" href="/admin/dashboard?status=0">Cancelled</a>
          <a class="dropdown-item" href="/admin/dashboard?status=3">Completed</a>
        </div>
      </div>
    </li>
  </ul>
</nav>
<header class=''></header>
<div class="">
  <section class="container-fluid">
    <div class="row">
      <div class="col-3"></div>
      <table class="table table-striped col-6 margin-right-20">
        <thead class="bg-secondary text-white" id="max-temps">
          <tr>
            <% @status_totals.each do |status, total| %>
              <th scope="col"><%= status.titleize %> Orders: <%= total %></th>
            <% end %>
            <% (4 - @status_totals.length).times do |thing| %>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>
        <thead class="thead-dark">
          <tr>
            <th scope="col">Orders</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= link_to "Order Id: #{order.id}", order_path(order) %></td>
            <td>Status: <%= order.status.titleize %></td>
            <% if order.status.downcase == 'ordered' %>
              <td class=""><%= button_to "Mark As Paid", admin_order_path(order, status: 2), method: :patch, class: 'btn btn-success' %></td>
            <% elsif order.status.downcase == 'paid' %>
              <td class=""><%= button_to "Mark As Completed", admin_order_path(order, status: 3), method: :patch, class: 'btn btn-success' %></td>
            <% else %>
              <td></td>
            <% end %>
            <% if order.status.downcase == 'paid' || order.status.downcase == 'ordered' %>
              <td><%= button_to "Cancel", admin_order_path(order, status: 0), method: :patch, class: 'btn btn-danger' %></td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
  <div class="d-flex justify-content-center pb-5"><%= link_to 'Edit Account Info', edit_user_path(current_user) %></div>
</div>