config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  get '/bike-shop', to: 'accessories#index'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/dashboard', to: 'users#dashboard'
  resources :users, only: [:new, :create, :edit, :update]
  resources :stations, only: [:index]
  resources :trips, only: [:show, :index]
  resources :conditions, only: [:index, :show]
  get '/conditions-dashboard', to: 'conditions#dashboard'
  resources :accessories, only: [:show]
  resources :carts, only: [:create]
  namespace :admin do
    resources :stations, only: [:new, :edit, :create, :update, :destroy]
    resources :trips, only: [:new, :edit, :create, :update, :destroy]
    resources :conditions, only: [:new, :edit, :create, :update, :destroy]
    resources :accessories, only: [:create, :edit, :update]
    resources :orders, only: [:update]
    get '/bike-shop/new', to: 'accessories#new'
    post '/bike-shop', to: 'accessories#create'
    get '/bike-shop', to: 'accessories#index'
  end
  get '/admin/dashboard', to: 'admin/users#dashboard'
  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  resources :orders, only: [:create, :show]
  get '/:id', to: 'stations#show', as: :station
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates_presence_of :description
  validates_presence_of :price
  has_many :order_accessories
  has_many :orders, through: :order_accessories
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  def show
    @accessory = Accessory.find(params[:id])
  end

  def index
    @accessories = Accessory.all 
  end
end

app/controllers/admin/accessories_controller.rb
class Admin::AccessoriesController < Admin::BaseController
  def index
    @accessories = Accessory.all
  end
  def new
    @accessory = Accessory.new
  end

  def create
    @accessory = Accessory.new(accessory_params)
    if @accessory.save
      flash[:notice] = "Successfully created #{@accessory.title}"
      redirect_to accessory_path(@accessory)
    else
      flash[:notice] = "Accessory not created. Try again."
      render :new
    end
  end

  def edit
    @accessory = Accessory.find(params[:id])
  end

  def update
    @accessory = Accessory.find(params[:id])
    if params[:retire] == 'true'
      @accessory.update!(retired?: true)
      flash[:notice] = "Successfully retired #{@accessory.title}"
      redirect_to admin_bike_shop_path
    elsif params[:retire] == 'false'
      @accessory.update(retired?: false)
      flash[:notice] = "Successfully activated #{@accessory.title}"
      redirect_to admin_bike_shop_path
    elsif @accessory.update(accessory_params)
      flash[:notice] = "Successfully updated #{@accessory.title}"
      redirect_to accessory_path(@accessory)
    else
      flash[:notice] = "Accessory not updated. Try again."
      render :edit
    end
  end

  def destroy
  end

  private

  def accessory_params
    params[:accessory][:image] = 'https://www.hsjaa.com/images/joomlart/demo/default.jpg' unless params[:image]
    params.require(:accessory).permit(:title, :description, :price, :image)
  end
end

app/views/accessories/index.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'>Bike Shop</h1>
  <% if admin_user? %>
    <%= link_to 'Create New Accessory', admin_bike_shop_new_path, class:'btn btn-secondary button-link' %>
  <% end %>
</header>

<div class="bikeshop-subheader">
  <% if admin_user? %>
    <%= link_to 'Admin Bike Shop', admin_bike_shop_path, class:'btn btn-info admin-bikeshop-button' %>
  <% end %>
</div>

<section class='station-index-main'>
  <table class="table table-striped table-ligth" id='station-index-table'>
    <thead class='table-light table-header'>
      <tr>
        <th scope="col" id='table-entry'></th>
        <th scope="col" id='table-entry'>Accessory</th>
        <th scope="col" id='table-entry'>Description</th>
        <th scope="col" id='table-entry'>Price</th>
        <th scope="col" id='table-entry'></th>
        <% if admin_user? %>
          <th scope="col" id='table-entry'></th>
          <th scope="col" id='table-entry'></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @accessories.each do |accessory| %>
        <tr class="accessory-<%= accessory.id %>"<%= accessory.id %>>
          <th id='table-entry'><img src="<%= accessory.image %>" alt="thumbail" style="width:30px;height:30px;"></th>
          <th id='table-entry'><%= link_to accessory.title, accessory_path(accessory) %></th>
          <td id='table-entry'><%= accessory.description %></td>
          <td id='table-entry'><%= number_to_currency(accessory.price) %></td>
          <% if accessory.retired? %>
            <td><%= button_to 'Retired', nil, disabled: true, class:'btn btn-outline-dark retired-button' %></td>
          <% else %>
            <td><%= button_to "Add to Cart", carts_path(accessory_id: accessory.id), class:'btn btn-primary' %></td>
          <% end %>
          <% if admin_user? %>
            <td><%= button_to 'Edit', edit_admin_accessory_path(accessory), method: :get, class:'btn btn-success' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/accessories/show.html.erb
<header class='jumbotron' id='header'>
  <h1 class='text-white'><%= @accessory.title %></h1>
  <% if admin_user? %>
    <%= link_to 'Create New Accessory', admin_bike_shop_new_path, class:'btn btn-secondary button-link' %>
  <% end %>
</header>

<div class="accessory-show-subheader">
  <div class='accessory-show-buttons'>
    <% if admin_user? %>
    <%= button_to 'Edit', edit_admin_accessory_path(@accessory), method: :get, class:'btn btn-success show-edit-button' %>
    <%= button_to 'Delete', admin_accessory_path(@accessory), method: :delete, data: {confirm: "Really want to delete this station?"}, class:'btn btn-danger' %>
    <% end %>
  </div>
</div>

<section class='show-main mb-5'>
  <div class=accessory-card>
    <div class="card">
      <img class="card-img-top" src='<%= @accessory.image %>' alt="Card image cap" style="width:400px;height:400px;">
      <div class="card-body">
        <h3 class="card-title"><%= @accessory.title %></h3>
        <p class="card-text"><%= @accessory.description %></p>
        <p class='card-text'><%= number_to_currency(@accessory.price) %></p>
        <% if @accessory.retired? %>
          <p><%= button_to 'Retired', nil, disabled: true, class:'btn btn-outline-dark retired-button' %></p>
        <% else %>
          <p><%= button_to 'Add to Cart', carts_path(accessory_id: @accessory.id, on_show: true), class:'btn btn-primary' %></p>
        <% end %>
        <% if admin_user? %>
          <% if @accessory.retired? %>
            <td><%= button_to 'Activate', admin_accessory_path(@accessory, retire: 'false'), method: :patch, class:'btn btn-primary accessory-show-button-activate' %></td>
          <% else %>
            <td><%= button_to 'Retire', admin_accessory_path(@accessory, retire: 'true'), method: :patch, class:'btn btn-danger index-retire-button accessory-show-button-retire' %></td>
          <% end %>
        <% end %>
        <%= link_to '<< Back to Bike Shop', bike_shop_path %>
      </div>
    </div>
  </div>
</section>